### ISSUE TITLE
Supporting SmartGit

### ISSUE THREAD

**Issue by The-Futurist** [dg9ngf/NetRevisionTool#11]
Hi,

I looked a coworkers machine (on which NetRevisionTool was not finding Git) and here is where SmartGit had installed Git:

C:\Program Files (x86)\SmartGit\git\bin\git.exe 

For some reason, SmartGit installs that surreptitiously in its own folder.

Thanks

@ygoe

**Comment by ygoe** [comment]
I've added this to the search strategy. Please let me know if it works for you.
