### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by The-Futurist** [dg9ngf/NetRevisionTool#12]
Hi,

Thanks for making those recent changes by the way.

We want to include a time-zone for the time setting strings, here's why - we have developers onshore (AZ Usa) and offshore (India). If we use local time in our projects then stuff we build locally will have a meaningful time but stuff built offshore will have a time pertaining to the local time in India which will eventually confuse us all.

Therefore we've been using UTC but of course that time (although consistent whether built onshore/offshore) is also a bit confusing for support staff here in AZ.

So we'd therefore like to have the times be local AZ time no matter who builds the code.

I could do this and create a pull request or if you feel you'd like to do it, then that's fine - please let me know.

Thx

**Comment by ygoe** [comment]
That would require extensive support for specifying time zones and their correct zone data. How would you tackle this? For one, there's this stupid thing as DST and its change dates are different for every region of the world. A static offset in hours won't work.

**Comment by The-Futurist** [comment]
@ygoe - Yes, it isn't trivial I agree. I've just tweaked the tool code locally, so we adjust for 'Mountain Standard Time". That is I hard-coded this into the tool - for time being.

What about simply adding optional cmd line arg to accept a time zone name string?

@ygoe 
My tweak is to ensure the time and date specs are prefixed "u" (UTC) and then simply adjusting that UTC zone by the specified time zone name string. In other words the time adjustment is only made if the assembly info is using "u" prefixed date/time.

I pushed this to my fork for you to see, in theory we could just make that time zone string a cmd line arg...

(For some reason force push to my fork is failing, I'll look at this later, so here's the code:)


Line 167 in RevisionFormat.cs:

`				case SchemeType.Readable:
     if (data.Utc)
	{
        var zone = TimeZoneInfo.FindSystemTimeZoneById("Mountain Standard Time");
        time = time.UtcDateTime;
        time = TimeZoneInfo.ConvertTimeFromUtc(time.DateTime, zone);
	}

`

**Comment by ygoe** [comment]
Just did this short test:

```
> var zone = TimeZoneInfo.FindSystemTimeZoneById("Mountain Standard Time");
> TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, zone);
16.01.2017 10:58:06
> TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow.AddMonths(6), zone);
16.07.2017 11:58:27
```

Seems to work, for both standard and daylight saving time, also on non-English Windows systems (mine is German). I'd rather not touch the "u" prefix and instead consider all non-UTC time output in the provided time zone, if any.

**Comment by The-Futurist** [comment]
@ygoe 

I agree that "u" should be left out of this (I just tweaked this to get what I want without me needing to update all of the projects' AssemblyInfo files).  Anyway, I am puzzled why Microsoft didn't just create a huge enum for these:

https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations

**Comment by ygoe** [comment]
This tool is not in development anymore. Please use NetRevisionTask in my other repository.
