### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by The-Futurist** [dg9ngf/NetRevisionTool#14]
Hi,

Do you think its possible to also get the name of the repo? we have multiple repos and sometimes branch/commit ID is not always obvious to some staff who want to get to our code. 

Being able to include repo name would be HUGE for us!

Thx

**Comment by ygoe** [comment]
For SVN you can determine the repository URL, that's all there is. For Git, you'd first have to specify a remote name to get its URL. Git repositories don't have such a thing as names. Maybe you could use the build machine name instead? That was added in v2.6.

**Comment by The-Futurist** [comment]
Hi @ygoe 

Yes you're right but I'd like to at least use the name of the repos root folder, in our team every developer calls their local repos the same name as the upstream repo.

For example this command gives us the path of the repo root folder:

git rev-parse --show-toplevel

if we then stripped off everything but the last component of that path, we'd have the repo folder name.

Is this easy (I've not looked at the code recently, so apologies if this is an easy chg)

**Comment by hgleaves-ncuadmin** [comment]
Hi @ygoe 

I created a PR that shows how I made the change in my fork, there may be a better way, but this does the trick for us.

**Comment by The-Futurist** [comment]
Hi @ygoe

I created a PR that shows how I made the change in my fork, there may be a better way, but this does the trick for us.
