### ISSUE TITLE
Support ability to include commit URL

### ISSUE THREAD

**Issue by The-Futurist** [dg9ngf/NetRevisionTool#17]
Hi,

I'm thinking about adding a new capability here, one that lets us specify (in the command args) the URL of our organization. Then because I already added support for getting repo name {repodir} it's possible to construct the URL to a commit and embed this in the ProductVersion attribute.

Do you have any concerns or reservations about this in general?

**Comment by ygoe** [comment]
I don't understand it. What is the URL of your organisation? Is that the fixed domain name of your company's web site? Why would that be dynamic? And what does it have to do with the absolute local path of the repo that was built from? (#14)

**Comment by The-Futurist** [comment]
@ygoe - Hi,

I'm talking about my company's Github organization (e.g this is Microsoft's https://github.com/microsoft/ ) Making this a new command line option means that at runtime the tool can build a full URL for the commit:

e.g.

https://github.com/Microsoft/vscode/commit/09300167973f0093814b733060baf0a5763a8926

This is the org url "https://github.com/Microsoft" and the repo name "vscode" (this is now supported) and the word "commit" and then we'd append the 8 chars of the commit ID "09300167".

Thus the tool could create this full URL and with another placeholder {commiturl} this could be included in the attribute and available to other tools.

I'm working on a shell extension tool that we can right-click-properties on a DLL here and it will display the details of the attribute it will also display (if present) this URL so the user sitting at a desktop can just click and be taken to the commit in Github !

We're are using this build stamp a lot here and its proving very useful to us in understanding and resolving questions about qa, prod etc.

This is where my pull requests are coming from, real world day to day use cases.

**Comment by ygoe** [comment]
Okay, but what's the difference if you just put that base URL as static text in your assembly version info? What advantage does it have to provide it to NetRevisionTool instead (after all it must be provided and cannot be automatically determined – which NetRevisionTool is all about) and have it passed through in that specific way?

**Comment by The-Futurist** [comment]
@ygoe - OK yes you're quite right that is a simpler way to do it, I'm looking at this now too...

**Comment by The-Futurist** [comment]
@ygoe - Yep I was being dumb! This required no change (other than stuff you'll see in my pending PRs) I just edited the AssemblyInfo,cs - everything we need is already there - also when the build data is echoed to Output window, you can ctrl-click the displayed URL and VS opens its browser window at the Github commit!

**Comment by The-Futurist** [comment]
@ygoe - Bascially I just added this (for example) to the assembly info

https://github.com/ygoe/{repodir}/commit/{CHASH:16}

**Comment by ygoe** [comment]
Glad to hear it's working for you!
