### ISSUE TITLE
Empty commit ID, missing output values.

### ISSUE THREAD

**Issue by The-Futurist** [dg9ngf/NetRevisionTool#7]
We are just rolling out updates to our projects to include use of your tool. This all went fine when I initially tested it out on a sample project.

But on a coworker's machine we added the same changes to a different project but get odd results after the build.

Here is the assembly info string we're using:

[assembly: AssemblyInformationalVersion("{b:uymd-} {b:uhms:} -> {cname} -> {branch} -> {CHASH:8} {!:(Warning - There were uncommited changes present)}")] 

But here's the output we see for the generated assembly:

2016-10-24 18:39:33 -> -> -> 00000000

His project sits within a local Git repo just as mine does, but I see all of the expected values in my generated DLL but his are missing and has commit ID all zeros, no branch name or committer name.

It's as if the tool is unaware of his repo or has no access to its metadata, but I don't know how this could happen.

The build output window reports no errors or warnings and we use Visual Studio 2015 and 2013.

**Comment by The-Futurist** [comment]
OK we found a cause. We use SmartGit and some of us do not have Github extensions for Visual Studio installed. For these developers the tool was unable to find Git on their machine (SmartGit installs it but privately).

So we're fine now, but it would be good to log a build warning for this or include a some new option {nogit:<some message>} that causes the AssemblyInfoVersion to get set to that message if Git isn't found by NetRevisionTool.

(The core problem was that Git for Windows hadn't been installed, only the (private) install that SmartGit installs, there's no need for Github extensions for VS, although installing this does install Git for Windows).

**Comment by ygoe** [comment]
You can enable debug output and see what it finds and where. This would have told you about the problem. Since NetRevisionTool supports multiple VCS, not all of them need to be installed. And only those that are installed (and discovered) can be used to recognise repositories.

**Comment by viktoreinars** [comment]
I had the same problem. We use SourceTree and therefor the executable is unable to find the git executable.

I managed to get it working by copying the git.exe and a library dll to the working directory.

An idea would be to allow to specify a git working directory (there is an embedded git within SourceTree).

**Comment by ygoe** [comment]
@Korporal @viktoreinars Could you please tell me where git.exe is located on your systems with only the other Git client installed? I think it would be best to include these (and later more) locations in NetRevisionTool's search strategy so that it just works for you and everyone who uses the same Git client.

**Comment by viktoreinars** [comment]
@Korporal: See my StackOverflow comments: http://stackoverflow.com/a/29209759/392583
